### Add User
POST {{Host}}/api/v1/User
Accept: application/json
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "tenantId": "tenant-123"
}

### Remove User
DELETE {{Host}}/api/v1.0/User/john.doe@example.com
Accept: application/json


###
