### Add User
POST {{Host}}/api/v1/User
Accept: application/json
Content-Type: application/json
X-Api-Key: SecretApiKey123

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "identityProviderId": "auth0|123",
  "tenantId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}

### Get User
GET {{Host}}/api/v1/User/john.doe@example.com
Accept: application/json
X-Api-Key: SecretApiKey123

### Remove User
DELETE {{Host}}/api/v1.0/User/john.doe@example.com
Accept: application/json
X-Api-Key: SecretApiKey123


###
